### ISSUE TITLE
Usuwanie submission

### ISSUE THREAD

**Issue by mattyl006** [amu-cai/gonito-backend#12]
- add field _deleted_ in the _Submission_ table that holds boolean value
- make sure the endpoint for the submission return returns the _deleted_ value
- add endpoint for _deleting_ a submission, i.e. setting _True_ in _deleted_ field
- endpoint: post '/api/delete-submission/{submission-id}'

**Comment by mattyl006** [comment]
Jeszcze do dorobienia, zwracanie wartości True or False, w zależności czy proces usuwania submission się powiódł czy nie

**Comment by flaizdnag** [comment]
Zwracany jest string, np. "deleted"
