### ISSUE TITLE
Edytowanie submission

### ISSUE THREAD

**Issue by flaizdnag** [amu-cai/gonito-backend#4]
Add endpoint for changing

- 'description' field in 'Submission' table
- 'tag' field in 'SubmissionTag' table
- endpoint name: post /api/edit-submission/{submission-id}

**Comment by mattyl006** [comment]
- otrzymane zostanie z Frontendu submissionId
- otrzymane zostanie z Frontendu "description" i zostaje one podmieniane
- otrzymane zostanie z Frontendu lista tagId, które ustawiamy jako nowe tagi danego submission, stare tagi zostają usunięte
